DROP TABLE IF EXISTS  T_USER ;
CREATE TABLE T_USER (
	USER_ID VARCHAR(30) PRIMARY KEY , 
	USER_PW VARCHAR(30) , 
	USER_NM VARCHAR(30) , 
	REGIST_DATE TIMESTAMP , 
	UPDATE_DATE TIMESTAMP
);
ALTER TABLE T_USER CONVERT TO CHARACTER SET UTF8;

DROP TABLE IF EXISTS  T_USER_TOKEN ;
CREATE TABLE T_USER_TOKEN (
	TOKEN VARCHAR(30) PRIMARY KEY,
	USER_ID VARCHAR(30) , 
	REGIST_DATE TIMESTAMP , 
	UPDATE_DATE TIMESTAMP
);
ALTER TABLE T_USER_TOKEN CONVERT TO CHARACTER SET UTF8;

DROP TABLE IF EXISTS  T_USER_LIKE ;
CREATE TABLE T_USER_LIKE (
	LIKE_ID VARCHAR(30) PRIMARY KEY,
	MAPPING_ID VARCHAR(30) , 
	REGIST_DATE TIMESTAMP , 
	UPDATE_DATE TIMESTAMP 
) ; 
ALTER TABLE T_USER_LIKE CONVERT TO CHARACTER SET UTF8; 
ALTER TABLE T_USER_LIKE ADD INDEX USER_LIKE_MAPPING (MAPPING_ID);

DROP TABLE IF EXISTS  T_USER_WATCH_HIST;
CREATE TABLE T_USER_WATCH_HIST (
	USER_ID VARCHAR(30) , 
	PROGRAM_ID VARCHAR(30) , 
	PRODUCT_ID VARCHAR(30) , 
	REGIST_DATE TIMESTAMP DEFAULT NOW(), 
	UPDATE_DATE TIMESTAMP , 
	PRIMARY KEY (USER_ID , PROGRAM_ID , PRODUCT_ID)
) ; 
ALTER TABLE T_USER_WATCH_HIST CONVERT TO CHARACTER SET UTF8;

DROP TABLE IF EXISTS  T_PROGRAM ;
CREATE TABLE T_PROGRAM (
	PROGRAM_ID VARCHAR(30) PRIMARY KEY ,
	TITLE VARCHAR(100) , 
	PROGRAM_TYPE VARCHAR(30) , 
	SYNOPSIS VARCHAR(200) , 
	WATCH_COUNT INT ,
	REGIST_DATE TIMESTAMP , 
	UPDATE_DATE TIMESTAMP 
) ;
ALTER TABLE T_PROGRAM CONVERT TO CHARACTER SET UTF8;

DROP TABLE IF EXISTS  T_PROGRAM_PRODUCT ; 
CREATE TABLE T_PROGRAM_PRODUCT ( 
	PROGRAM_ID VARCHAR(30) ,
	PRODUCT_ID VARCHAR(30) , 
	TITLE VARCHAR(100) , 
	TEXT VARCHAR(1000) , 
	SEASON VARCHAR(10) , 
	EPISODE VARCHAR(10) , 
	REGIST_DATE TIMESTAMP , 
	UPDATE_DATE TIMESTAMP , 
	PRIMARY KEY (PROGRAM_ID , PRODUCT_ID)
) ;
ALTER TABLE T_PROGRAM_PRODUCT CONVERT TO CHARACTER SET UTF8; 

DROP TABLE IF EXISTS  T_GENRE ; 
CREATE TABLE T_GENRE(
	GENRE_ID VARCHAR(30) PRIMARY KEY , 
	GENRE_NAME VARCHAR(100) , 
	REGIST_DATE TIMESTAMP , 
	UPDATE_DATE TIMESTAMP 
);
ALTER TABLE T_GENRE CONVERT TO CHARACTER SET UTF8;

DROP TABLE IF EXISTS  T_PROGRAM_GENRE ; 
CREATE TABLE T_PROGRAM_GENRE (
	PROGRAM_ID VARCHAR(30) , 
	GENRE_ID VARCHAR(30) ,
	REGIST_DATE TIMESTAMP , 
	UPDATE_DATE TIMESTAMP,
	PRIMARY KEY ( GENRE_ID , PROGRAM_ID )
) ;
ALTER TABLE T_PROGRAM_GENRE CONVERT TO CHARACTER SET UTF8;

DROP TABLE IF EXISTS  T_CONTENT ; 
CREATE TABLE T_CONTENT (
	CONTENT_ID VARCHAR(30) PRIMARY KEY , 
	CONTENT_NAME VARCHAR(100) ,
	CONTENT_TYPE VARCHAR(30) , 
	SORT_SN INT DEFAULT 99 , 
	USE_AT VARCHAR(1) DEFAULT 'Y',
	REGIST_DATE TIMESTAMP , 
	UPDATE_DATE TIMESTAMP
) ;
ALTER TABLE T_CONTENT CONVERT TO CHARACTER SET UTF8;

DROP TABLE IF EXISTS  T_CONTENT_PROGRAM ; 
CREATE TABLE T_CONTENT_PROGRAM (
	CONTENT_ID VARCHAR(30) , 
	PROGRAM_ID VARCHAR(30) ,
	CONTENT_TYPE VARCHAR(100) , 
	SORT_SN INT , 
	REGIST_DATE TIMESTAMP , 
	UPDATE_DATE TIMESTAMP , 
	PRIMARY KEY ( CONTENT_ID , PROGRAM_ID ) 
) ;
ALTER TABLE T_CONTENT_PROGRAM CONVERT TO CHARACTER SET UTF8;

DROP TABLE IF EXISTS  T_IMAGE_META ; 
CREATE TABLE T_IMAGE_META (
	IMAGE_ID VARCHAR(30) PRIMARY KEY, 
	MAPPING_ID VARCHAR(30) ,
	IMAGE_TYPE VARCHAR(100) , 
	REGIST_DATE TIMESTAMP , 
	UPDATE_DATE TIMESTAMP
) ;
ALTER TABLE T_IMAGE_META CONVERT TO CHARACTER SET UTF8;
ALTER TABLE T_IMAGE_META ADD INDEX IMAGE_MAPPING (MAPPING_ID);

DROP TABLE IF EXISTS  T_TIMELINE ; 
CREATE TABLE T_TIMELINE ( 
	TIMELINE_ID VARCHAR(30) PRIMARY KEY ,
	TITLE VARCHAR(100) ,
	TEXT VARCHAR(1000) ,  
	REGIST_DATE TIMESTAMP , 
	UPDATE_DATE TIMESTAMP
) ;
ALTER TABLE T_TIMELINE CONVERT TO CHARACTER SET UTF8; 

DROP TABLE IF EXISTS  T_TIMELINE_PROGRAM ; 
CREATE TABLE T_TIMELINE_PROGRAM ( 
	TIMELINE_ID VARCHAR(30) ,
	PROGRAM_ID VARCHAR(30) , 
	REGIST_DATE TIMESTAMP , 
	UPDATE_DATE TIMESTAMP ,
	PRIMARY KEY (TIMELINE_ID , PROGRAM_ID )
) ;
ALTER TABLE T_TIMELINE_PROGRAM CONVERT TO CHARACTER SET UTF8; 