INSERT INTO T_USER VALUES ( 'kingroma', '4235' ,'kjj', NOW() , now()) ;
insert into T_USER_TOKEN values ( '7DKjtfw4ArN2HlrGq3Tl','kingroma',now(),now()) ;

-- PROGRAM_ID , TITLE , PROGRAM_TYPE , SYNOPSIS , WATCH_COUNT , REGIST_DATE , UPDATE_DATE 
INSERT INTO T_PROGRAM VALUES( '1','TITLE1','basic','synopsis1',1,now(),now());
INSERT INTO T_PROGRAM VALUES( '2','TITLE2','series','synopsis2',6,now(),now());
INSERT INTO T_PROGRAM VALUES( '3','TITLE13','basic','synopsis3',1,now(),now());
INSERT INTO T_PROGRAM VALUES( '4','TITLE4','basic','synopsis4',1,now(),now());
INSERT INTO T_PROGRAM VALUES( '5','TITLE51','basic','synopsis5',3,now(),now());
INSERT INTO T_PROGRAM VALUES( '6','TITLE6','basic','synopsis16',1,now(),now());
INSERT INTO T_PROGRAM VALUES( '7','TITLE7','basic','synopsis17',1,now(),now());
INSERT INTO T_PROGRAM VALUES( '8','TITLE8','series','synopsis8',5,now(),now());
INSERT INTO T_PROGRAM VALUES( '9','TITLE9','basic','synopsis19',1,now(),now());



-- PROGRAM_ID , PRODUCT_ID , TITLE , TEXT , SEASON , EPISODE , REGIST_DATE , UPDATE_DATE 
INSERT INTO T_PROGRAM_PRODUCT VALUES ( '1','1' ,'TITL1','TEXT24',NULL,NULL,NOW(),NOW()) ;
INSERT INTO T_PROGRAM_PRODUCT VALUES ( '2','2' ,'TITL2','TEXT23',1,1,NOW(),NOW()) ;
INSERT INTO T_PROGRAM_PRODUCT VALUES ( '2','3' ,'TITL4','TEXT22',1,2,NOW(),NOW()) ;
INSERT INTO T_PROGRAM_PRODUCT VALUES ( '2','4' ,'TITL6','TEXT21',2,1,NOW(),NOW()) ;
INSERT INTO T_PROGRAM_PRODUCT VALUES ( '3','5' ,'TITL6','TEXT20',NULL,NULL,NOW(),NOW()) ;
INSERT INTO T_PROGRAM_PRODUCT VALUES ( '4','6' ,'TITL3','TEXT19',NULL,NULL,NOW(),NOW()) ;
INSERT INTO T_PROGRAM_PRODUCT VALUES ( '5','7' ,'TITL1','TEXT18',NULL,NULL,NOW(),NOW()) ;
INSERT INTO T_PROGRAM_PRODUCT VALUES ( '6','8' ,'TITL1','TEXT17',NULL,NULL,NOW(),NOW()) ;
INSERT INTO T_PROGRAM_PRODUCT VALUES ( '7','9' ,'TITL1','TEXT16',NULL,NULL,NOW(),NOW()) ;
INSERT INTO T_PROGRAM_PRODUCT VALUES ( '8','10','TITL1','TEXT15',1,1,NOW(),NOW()) ;
INSERT INTO T_PROGRAM_PRODUCT VALUES ( '8','11','TITL2','TEXT14',1,2,NOW(),NOW()) ;
INSERT INTO T_PROGRAM_PRODUCT VALUES ( '8','12','TITL1','TEXT13',1,3,NOW(),NOW()) ;
INSERT INTO T_PROGRAM_PRODUCT VALUES ( '9','13','TITL1','TEXT12',NULL,NULL,NOW(),NOW()) ;


-- GENRE_ID , GENRE_NAME , REGIST_DATE , UPDATE_DATE 
INSERT INTO T_GENRE VALUES ('1','NM1',NOW(),NOW()) ;
INSERT INTO T_GENRE VALUES ('2','NM8',NOW(),NOW()) ;
INSERT INTO T_GENRE VALUES ('3','NM7',NOW(),NOW()) ;
INSERT INTO T_GENRE VALUES ('4','NM6',NOW(),NOW()) ;
INSERT INTO T_GENRE VALUES ('5','NM5',NOW(),NOW()) ;
INSERT INTO T_GENRE VALUES ('6','NM4',NOW(),NOW()) ;
INSERT INTO T_GENRE VALUES ('7','NM3',NOW(),NOW()) ;
INSERT INTO T_GENRE VALUES ('8','NM2',NOW(),NOW()) ;


-- PROGRAM_ID , GENRE_ID 
INSERT INTO T_PROGRAM_GENRE VALUES ( '1' , '1' , NOW(), NOW());
INSERT INTO T_PROGRAM_GENRE VALUES ( '2' , '2' , NOW(), NOW());
INSERT INTO T_PROGRAM_GENRE VALUES ( '3' , '3' , NOW(), NOW());
INSERT INTO T_PROGRAM_GENRE VALUES ( '4' , '4' , NOW(), NOW());
INSERT INTO T_PROGRAM_GENRE VALUES ( '5' , '5' , NOW(), NOW());
INSERT INTO T_PROGRAM_GENRE VALUES ( '6' , '6' , NOW(), NOW());
INSERT INTO T_PROGRAM_GENRE VALUES ( '7' , '7' , NOW(), NOW());
INSERT INTO T_PROGRAM_GENRE VALUES ( '8' , '8' , NOW(), NOW());
INSERT INTO T_PROGRAM_GENRE VALUES ( '9' , '1' , NOW(), NOW());
INSERT INTO T_PROGRAM_GENRE VALUES ( '1' , '5' , NOW(), NOW());
INSERT INTO T_PROGRAM_GENRE VALUES ( '6' , '2' , NOW(), NOW());
INSERT INTO T_PROGRAM_GENRE VALUES ( '3' , '1' , NOW(), NOW());
INSERT INTO T_PROGRAM_GENRE VALUES ( '7' , '2' , NOW(), NOW());


-- CONTENT_ID , CONTENT_NAME , CONTENT_TYPE , SORT_SN , USE_AT 
INSERT INTO T_CONTENT VALUES ('1','CONTENT1','basic',1,'Y',NOW(),NOW()) ;
INSERT INTO T_CONTENT VALUES ('2','CONTENT2','basic',7,'Y',NOW(),NOW()) ;
INSERT INTO T_CONTENT VALUES ('3','CONTENT3','basic',6,'Y',NOW(),NOW()) ;
INSERT INTO T_CONTENT VALUES ('4','CONTENT4','basic',5,'Y',NOW(),NOW()) ;
INSERT INTO T_CONTENT VALUES ('5','CONTENT5','issue',4,'Y',NOW(),NOW()) ;
INSERT INTO T_CONTENT VALUES ('6','CONTENT6','basic',3,'Y',NOW(),NOW()) ;
INSERT INTO T_CONTENT VALUES ('7','CONTENT7','top',2,'Y',NOW(),NOW()) ;

-- CONTENT_ID , PROGRAM_ID , CONTENT_TYPE , SORT_SN 
INSERT INTO T_CONTENT_PROGRAM VALUES ( '1' , '1' , NULL , 3 , NOW(), NOW());
INSERT INTO T_CONTENT_PROGRAM VALUES ( '1' , '2' , NULL , 1 , NOW(), NOW());
INSERT INTO T_CONTENT_PROGRAM VALUES ( '1' , '3' , NULL , 2 , NOW(), NOW());
INSERT INTO T_CONTENT_PROGRAM VALUES ( '1' , '4' , NULL , 3 , NOW(), NOW());
INSERT INTO T_CONTENT_PROGRAM VALUES ( '1' , '5' , NULL , 4 , NOW(), NOW());
INSERT INTO T_CONTENT_PROGRAM VALUES ( '2' , '6' , NULL , 5 , NOW(), NOW());
INSERT INTO T_CONTENT_PROGRAM VALUES ( '2' , '7' , NULL , 6 , NOW(), NOW());
INSERT INTO T_CONTENT_PROGRAM VALUES ( '2' , '8' , NULL , 1 , NOW(), NOW());
INSERT INTO T_CONTENT_PROGRAM VALUES ( '3' , '1' , NULL , 2 , NOW(), NOW());
INSERT INTO T_CONTENT_PROGRAM VALUES ( '3' , '2' , NULL , 3 , NOW(), NOW());
INSERT INTO T_CONTENT_PROGRAM VALUES ( '4' , '3' , NULL , 4 , NOW(), NOW());
INSERT INTO T_CONTENT_PROGRAM VALUES ( '4' , '4' , NULL , 5 , NOW(), NOW());
INSERT INTO T_CONTENT_PROGRAM VALUES ( '4' , '5' , NULL , 1 , NOW(), NOW());
INSERT INTO T_CONTENT_PROGRAM VALUES ( '4' , '6' , NULL , 2 , NOW(), NOW());
INSERT INTO T_CONTENT_PROGRAM VALUES ( '5' , '3' , NULL , 1 , NOW(), NOW());
INSERT INTO T_CONTENT_PROGRAM VALUES ( '6' , '2' , NULL , 2 , NOW(), NOW());
INSERT INTO T_CONTENT_PROGRAM VALUES ( '7' , '1' , NULL , 3 , NOW(), NOW());